# Generated by Django 4.1.7 on 2023-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CUSTOMER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
