# Generated by Django 4.1.7 on 2023-08-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('SALES_ORDER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AMOUNT', models.IntegerField()),
                ('CUSTOMER_ID', models.ForeignKey(db_column='CUSTOMER_ID', on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
            ],
        ),
    ]
